amalik17/rails-airbnb-clone

- Gemfile
- Gemfile.lock
- config/database.yml
- db/schema.rb
I set up devise in the gemfile, then I set up the User model using devise and generated the views for devise as well. A word of caution, I had to configure database.yml in my config file in order to get it to work on Linux so that may also be a potential conflict
> Added devise to gemfile

- config/database.yml
@kikinz amended the database.yml file for macs
> changed database.yml file for mac configurations

- app/controllers/acts_controller.rb
- config/database.yml
- config/routes.rb
I removed the incomplete WIP for acts routes good_for and genre
I changed up the config/database.yml to use environmental variables and application.yml is being ignored
> Complete acts routes

- app/controllers/acts_controller.rb
- config/database.yml
- config/routes.rb
I finished the crud actions for acts and added the filter actions good_for and genre
> Finished crud actions for acts

- app/views/acts/index.html.erb
set up index card to show attributes of individual act
> Index card is showing act attributes

- db/seeds.rb
@amalik17 Added 10 seeds for Acts
> added 10 seeds for acts

- Gemfile
> added gems for cloudinary, attachinary, and faker

- Gemfile
@amalik17 updated the gems for cloudinary and attachinary to the ones lewagon instructed
> updated gems for cloudinary and attachinary

- db/seeds.rb
> amended seeds file

- Gemfile.lock
- app/models/act.rb
- app/models/booking.rb
- app/models/user.rb
- config/routes.rb
- db/migrate/20170620082902_create_bookings.rb
- db/migrate/20170620090040_add_booking_status_to_bookings.rb
- db/migrate/20170620090446_remove_booked_from_bookings.rb
- db/schema.rb
@amalik17 
added booking model
added shallow routes for bookings, but only: [:index, :show, :update]
added routes for bookings outside of acts for only: [:index, :new, :create, :destroy]
> added booking model and preliminary routes

- app/controllers/acts_controller.rb
- app/controllers/bookings_controller.rb
- app/views/bookings/create.html.erb
- app/views/bookings/destroy.html.erb
- app/views/bookings/edit.html.erb
- app/views/bookings/index.html.erb
- app/views/bookings/new.html.erb
- app/views/bookings/show.html.erb
- app/views/bookings/update.html.erb
- config/routes.rb
@amalik17 
Finished basic CRUDs for booking controller
Amended destroy actions and put the act_params inside private
> Add booking controller actions

- app/assets/stylesheets/components/_card.scss
- app/controllers/acts_controller.rb
- app/views/acts/index.html.erb
- app/views/acts/show.html.erb
- db/seeds.rb
Created filter option on index page (filter by genre or good_for)
Created links on individual cards to go to that act's show page
> Index filter

- app/views/shared/_footer.html.erb
- app/views/shared/_navbar.html.erb
> Fixed navbar

- app/assets/stylesheets/components/_alert.scss
- app/assets/stylesheets/components/_banner.scss
- app/controllers/bookings_controller.rb
- app/views/bookings/index.html.erb
added user dashboard (this was the bookings index page...not sure if we'll keep it at this route)
fixed some margin issues with .alert and .banner
> added some prelim styling to the user dashboard

- app/assets/stylesheets/components/_badges.scss
- app/assets/stylesheets/components/_button.scss
- app/views/shared/_navbar.html.erb
-changed the avatar in navigation to large version
-added a badge to the avatar (for future use with notifvications)
-added our app colors to the badge
@amalik17 @kikinz
> updated avatar component

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_index.scss
- app/views/acts/index.html.erb
@amalik17 @kikinz Added the buttons componenet with some preliminary styling.  Can amend later :)
> added css styling to buttons component

- app/views/shared/_navbar.html.erb
fixed some navbar issues that I accidentally made before
> fixed dropdown on desktop, and commented out the dashboard button

- app/assets/stylesheets/components/_button.scss
> updated purple button to be same as turqoise

- app/assets/stylesheets/config/_variables.scss
> Changed header font

- app/models/user.rb
- app/views/users/_form.html.erb
- app/views/users/edit.html.erb
- app/views/users/show.html.erb
- db/migrate/20170621025930_add_name_to_users.rb
- db/schema.rb
Added form for users#edit
Added show page for users (unfinished)
Added name field to Users db
> Add name to users

- config/routes.rb
Added shallow nesting for booking routes
> Added shallow nesting for booking routes

- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/users/_form.html.erb
- app/views/users/new.html.erb
Now that attachinary is working I updated the users model, controller, views with the attachinary information
> Updated users model, controller, views with attachinary information

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/views/acts/index.html.erb
- app/views/acts/new.html.erb
- app/views/layouts/application.html.erb
I centered the index page and added some styling to the create a new band form, the images aren't working on the index page cards though or connecting them with the new forms
> Center index page

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_media.scss
- app/assets/stylesheets/layout/_footer.scss
- app/assets/stylesheets/pages/_show.scss
- app/views/acts/show.html.erb
Updated acts#show view
Book now button is a placeholder for our booking form 
Acts#show view is ready for demo pending any changes on review
> Updated acts#show view

- app/assets/stylesheets/components/_alert.scss
- app/assets/stylesheets/layout/_utilities.scss
- app/views/acts/edit.html.erb
- app/views/acts/update.html.erb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/users/dashboard.html.erb
- app/views/users/edit.html.erb
- app/views/users/new.html.erb
> Finish form stylings

- app/controllers/acts_controller.rb
> added show page to devise whitelist

- app/assets/javascripts/application.js
- app/assets/stylesheets/components/_alert.scss
pasted in a JS code for the alert that fixed the gap and unpolished look
> fixed alert from nathan's code

- app/views/users/dashboard.html.erb
> fixed dashboard image with a conditional

- app/controllers/bookings_controller.rb
- app/views/acts/show.html.erb
- app/views/bookings/_form.html.erb
- app/views/bookings/edit.html.erb
- app/views/bookings/new.html.erb
- config/routes.rb
- db/migrate/20170622042432_add_user_reference_to_bookings.rb
- db/migrate/20170622043834_add_act_reference_to_bookings.rb
- db/migrate/20170622044138_remove_acts_reference_to_bookings.rb
- db/migrate/20170622044731_remove_users_reference_to_bookings.rb
- db/schema.rb
> Add booking function

- app/assets/stylesheets/components/_media.scss
- app/controllers/users_controller.rb
- app/views/acts/index.html.erb
- app/views/acts/show.html.erb
- app/views/users/dashboard.html.erb
Added a link from dashboard > acts you've created cards > acts#show view
Added edit button to acts#show view - NOTE: The edit button should only show if the act belongs to the user. If the act doesn't belong to the user the booking button should show. 
Updated index cards so the whole card is clickable.
> Added edit acts function

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_testimonial_card.scss
- app/views/devise/registrations/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/pages/home.html.erb
I finalized the styling for the home page and fixed the sign up and forgot password text coloring
> Home page final styling

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_listitem.scss
- app/controllers/users_controller.rb
- app/views/users/dashboard.html.erb
> polised dashboard, but no requested bookings

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_listitem.scss
- app/assets/stylesheets/pages/_dashboard.scss
- app/views/users/dashboard.html.erb
Updated styling for dashboard:
- added whitespace
- moved add an act button
- increased size of avatar
- added spacing between bio and edit button
- unstuck card from grey background
> Styling dashboard

- app/views/acts/index.html.erb
- app/views/users/show.html.erb
Removed edit button from profile (this will only be seen by people who are not the user)
> Updated profile page

- app/assets/stylesheets/layout/_utilities.scss
- app/assets/stylesheets/pages/_index.scss
- app/controllers/acts_controller.rb
- app/controllers/bookings_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/users_controller.rb
- app/views/acts/edit.html.erb
- app/views/acts/index.html.erb
- app/views/acts/new.html.erb
- app/views/bookings/edit.html.erb
- app/views/bookings/new.html.erb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
- app/views/users/dashboard.html.erb
- app/views/users/edit.html.erb
- app/views/users/new.html.erb
- db/seeds.rb
created final seeds file			
changed some minor items on homepage			
changed path to dashboard after book		
updated navbar			
updated dashboard items
> Finish seeds

- app/views/acts/show.html.erb
- app/views/users/dashboard.html.erb
- db/seeds.rb
> finished dashboard functions

- app/assets/stylesheets/layout/_footer.scss
- app/assets/stylesheets/pages/_show.scss
- app/views/acts/show.html.erb
- app/views/users/show.html.erb
Profile:
- fixed styling
Dashboard: 
- fixed styling
Acts#show:
- Hard coding reviews section
- Added button to link to profile (NOTE: Needs to be updated with user name instead of user_id)
> Updated profile, dashboard, acts#show views

- app/views/acts/show.html.erb
> Fixed broken link

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_testimonial_card.scss
- app/assets/stylesheets/pages/_index.scss
- app/controllers/acts_controller.rb
- app/views/acts/_form.html.erb
- app/views/acts/show.html.erb
- app/views/bookings/_form.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
- updated update method for acts
- removed mobile navbar
- changed background colour for testimonials on home page
- changed signup button to btn-lg on home page
> Quick fixes

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/layout/_utilities.scss
- app/views/acts/index.html.erb
- app/views/acts/show.html.erb
- app/views/bookings/_form.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
- app/views/users/dashboard.html.erb
- app/views/users/show.html.erb
> Small fixes
